/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prg371.project.bookings.presentation.frames;

import prg371.project.bookings.presentation.controllers.UserController;

/**
 *
 * @author User
 */
public class UserLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public UserLoginFrame() {
        initComponents();
    }
    
    private UserController userController = new UserController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpUserLogin = new javax.swing.JTabbedPane();
        tabLogin = new javax.swing.JPanel();
        lblLoginEmail = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        txtLoginEmail = new javax.swing.JTextField();
        txtLoginPassword = new javax.swing.JTextField();
        btnToRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        tabRegister = new javax.swing.JPanel();
        lblRegisterEmail = new javax.swing.JLabel();
        lblRegisterPassword = new javax.swing.JLabel();
        lblRegisterConfirmPassword = new javax.swing.JLabel();
        txtRegisterEmail = new javax.swing.JTextField();
        txtRegisterConfirmPassword = new javax.swing.JTextField();
        txtRegisterPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnToLogin = new javax.swing.JButton();
        tabExit = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpUserLogin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpUserLoginStateChanged(evt);
            }
        });

        lblLoginEmail.setText("Email:");

        lblLoginPassword.setText("Password:");

        btnToRegister.setText("To Register");
        btnToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToRegisterActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabLoginLayout = new javax.swing.GroupLayout(tabLogin);
        tabLogin.setLayout(tabLoginLayout);
        tabLoginLayout.setHorizontalGroup(
            tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabLoginLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnToRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabLoginLayout.createSequentialGroup()
                        .addGroup(tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoginPassword)
                            .addComponent(lblLoginEmail))
                        .addGap(18, 18, 18)
                        .addGroup(tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoginPassword))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        tabLoginLayout.setVerticalGroup(
            tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLoginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginEmail)
                    .addComponent(txtLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginPassword)
                    .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(tabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        tpUserLogin.addTab("Login", tabLogin);

        lblRegisterEmail.setText("Email:");

        lblRegisterPassword.setText("Password:");

        lblRegisterConfirmPassword.setText("Confirm Password:");

        txtRegisterPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterPasswordActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnToLogin.setText("To Login");
        btnToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabRegisterLayout = new javax.swing.GroupLayout(tabRegister);
        tabRegister.setLayout(tabRegisterLayout);
        tabRegisterLayout.setHorizontalGroup(
            tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabRegisterLayout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabRegisterLayout.createSequentialGroup()
                        .addComponent(lblRegisterConfirmPassword)
                        .addGap(18, 18, 18)
                        .addComponent(txtRegisterConfirmPassword))
                    .addGroup(tabRegisterLayout.createSequentialGroup()
                        .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegisterEmail)
                            .addComponent(lblRegisterPassword))
                        .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabRegisterLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(txtRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabRegisterLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        tabRegisterLayout.setVerticalGroup(
            tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRegisterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterEmail)
                    .addComponent(txtRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterPassword)
                    .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterConfirmPassword)
                    .addComponent(txtRegisterConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tpUserLogin.addTab("Register", tabRegister);

        javax.swing.GroupLayout tabExitLayout = new javax.swing.GroupLayout(tabExit);
        tabExit.setLayout(tabExitLayout);
        tabExitLayout.setHorizontalGroup(
            tabExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        tabExitLayout.setVerticalGroup(
            tabExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        tpUserLogin.addTab("Exit", tabExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpUserLogin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpUserLogin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        userController.handleLogin(this, txtLoginEmail.getText(), txtLoginPassword.getText());
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToRegisterActionPerformed
        tpUserLogin.setSelectedIndex(1);
    }//GEN-LAST:event_btnToRegisterActionPerformed

    private void txtRegisterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterPasswordActionPerformed
        
    }//GEN-LAST:event_txtRegisterPasswordActionPerformed

    private void btnToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLoginActionPerformed
        tpUserLogin.setSelectedIndex(0);
    }//GEN-LAST:event_btnToLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (userController.handleRegister(
            txtRegisterEmail.getText(),
            txtRegisterPassword.getText(),
            txtRegisterConfirmPassword.getText(),
            "Test"
        )) {
            tpUserLogin.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void tpUserLoginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpUserLoginStateChanged
        Object selectedComponent = tpUserLogin.getSelectedComponent();
        if (selectedComponent != null) {
            if (selectedComponent == tabExit) {
                System.exit(1);
            }
        }
    }//GEN-LAST:event_tpUserLoginStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnToLogin;
    private javax.swing.JButton btnToRegister;
    private javax.swing.JLabel lblLoginEmail;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblRegisterConfirmPassword;
    private javax.swing.JLabel lblRegisterEmail;
    private javax.swing.JLabel lblRegisterPassword;
    private javax.swing.JPanel tabExit;
    private javax.swing.JPanel tabLogin;
    private javax.swing.JPanel tabRegister;
    private javax.swing.JTabbedPane tpUserLogin;
    private javax.swing.JTextField txtLoginEmail;
    private javax.swing.JTextField txtLoginPassword;
    private javax.swing.JTextField txtRegisterConfirmPassword;
    private javax.swing.JTextField txtRegisterEmail;
    private javax.swing.JTextField txtRegisterPassword;
    // End of variables declaration//GEN-END:variables
}
